version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: sql_judge_db
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: sql_judge_platform
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sql_judge_queue
    ports:
      - "6379:6379"

volumes:
  postgres_data: